#!/bin/bash
#PBS -N 1_node_neat
#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -P CSCI1385
#PBS -q smp
#PBS -l walltime=01:30:00
#PBS -m abe
#PBS -M umair.nasir014@gmail.com


CWD=/mnt/lustre/users/mnasir/bp_walker
cd $CWD

module load chpc/python/anaconda/3-2019.10

source /apps/chpc/chem/anaconda3-2019.10/etc/profile.d/conda.sh

conda activate /home/mnasir/thesisGym

nproc=`cat $PBS_NODEFILE | wc -l`

python -u /mnt/lustre/users/mnasir/bp_walker/bipadel_walker.py

